version: '3.5'

services:
  hospitalserver:
    image: dulce/hospital-server:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Server/Dockerfile

  hospitalclient:
    image: dulce/hospital-client:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Client/Dockerfile
