version: '3.5'

services:
  userserver:
    image: dulce/hospital-server:prod
    build:
      context: ../../
      dockerfile: Environments/Production/Server/Dockerfile

  userclient:
    image: dulce/hospital-client:prod
    build:
      context: ../../
      dockerfile: Environments/Production/Client/Dockerfile
